=== kantsir/cdp/src/test/resources/dataset/xsd/mbank.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:simpleType name="dbtimetype">
		<xs:restriction base="xs:string">
			<xs:pattern
				value="((000[1-9])|(00[1-9][0-9])|(0[1-9][0-9]{2})|([1-9][0-9]{3}))-((0[1-9])|(1[012]))-((0[1-9])|([12][0-9])|(3[01])) (([01][0-9])|(2[0-3]))(:[0-5][0-9])(:[0-5][0-9])((\.[0-9]+)|)" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="clientactivestate">
		<xs:restriction base="xs:string">
			<xs:enumeration value="ACTIVE" />
			<xs:enumeration value="DELETED" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="clienttype">
		<xs:restriction base="xs:string">
			<xs:enumeration value="REGULAR" />
			<xs:enumeration value="GOLD" />
			<xs:enumeration value="PLATINUM" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="deposittype">
		<xs:restriction base="xs:string">
			<xs:enumeration value="SHORT" />
			<xs:enumeration value="LONG" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="account">
		<xs:attribute name="account_id" type="xs:integer" />
		<xs:attribute name="client_id" type="xs:integer" />
		<xs:attribute name="balance" type="xs:double" />
		<xs:attribute name="credit_limit" type="xs:double" />
		<xs:attribute name="comment" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="activity">
		<xs:attribute name="activity_id" type="xs:integer" />
		<xs:attribute name="activity_date" type="dbtimetype" />
		<xs:attribute name="client_id" type="xs:integer" />
		<xs:attribute name="amount" type="xs:double" />
		<xs:attribute name="commision" type="xs:double" />
		<xs:attribute name="description" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="client">
		<xs:attribute name="client_id" type="xs:integer" />
		<xs:attribute name="address" type="xs:string" />
		<xs:attribute name="client_name" type="xs:string" />
		<xs:attribute name="email" type="xs:string" />
		<xs:attribute name="password" type="xs:string" />
		<xs:attribute name="comment" type="xs:string" />
		<xs:attribute name="phone" type="xs:string" />
		<xs:attribute name="clientactivestate" type="clientactivestate" />
		<xs:attribute name="type" type="clienttype" />
	</xs:complexType>

	<xs:complexType name="deposit">
		<xs:attribute name="deposit_id" type="xs:integer" />
		<xs:attribute name="client_id" type="xs:integer" />
		<xs:attribute name="opening_date" type="dbtimetype" />
		<xs:attribute name="closing_date" type="dbtimetype" />
		<xs:attribute name="balance" type="xs:double" />
		<xs:attribute name="type" type="deposittype" />
	</xs:complexType>

	<xs:complexType name="property">
		<xs:attribute name="prop_key" type="xs:string" />
		<xs:attribute name="prop_value" type="xs:string" />
	</xs:complexType>


	<xs:element name="dataset">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element name="clients" type="client" maxOccurs="unbounded"  />
				<xs:element name="accounts" type="account" maxOccurs="unbounded" />
				<xs:element name="activities" type="activity" maxOccurs="unbounded" />
				<xs:element name="deposites" type="deposit" maxOccurs="unbounded" />
				<xs:element name="properties" type="property" maxOccurs="unbounded" />
			</xs:choice>
		</xs:complexType>
	</xs:element>


</xs:schema>

=== kantsir/cdp/src/test/resources/dataset/AdminService.DataSet.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="xsd/mbank.xsd">

	<clients address="testDatabaseFieldAddress1" client_name="testDatabaseFieldName1"
		comment="This is comments1" clientactivestate="ACTIVE"
		email="testDatabaseField1@testDatabaseField.com" password="testDatabaseFieldPassword1"
		phone="+1234567890" type="REGULAR" client_id="1" />
	<clients address="testDatabaseFieldAddress2" client_name="testDatabaseFieldName2"
		comment="This is comments2" clientactivestate="DELETED"
		email="testDatabaseField2@testDatabaseField.com" password="testDatabaseFieldPassword2"
		phone="+2345678901" type="GOLD" client_id="2" />
	<clients address="testDatabaseFieldAddress3" client_name="testDatabaseFieldName3"
		comment="This is comments3" clientactivestate="ACTIVE"
		email="testDatabaseField3@testDatabaseField.com" password="testDatabaseFieldPassword3"
		phone="+3456789012" type="PLATINUM" client_id="3" />

	<accounts balance="1.0" comment="comment1" credit_limit="1.0"
		client_id="1" account_id="1" />
	<accounts balance="2.0" comment="comment2" credit_limit="2.0"
		client_id="2" account_id="2" />
	<accounts balance="3.0" comment="comment3" credit_limit="3.0"
		client_id="3" account_id="3" />

	<activities activity_id="1" client_id="1" amount="1.0"
		commision="1.0" description="description1" activity_date="2012-01-11 11:11:11" />
	<activities activity_id="2" client_id="2" amount="2.0"
		commision="2.0" description="description2" activity_date="2012-02-12 12:12:12" />
	<activities activity_id="3" client_id="3" amount="3.0"
		commision="3.0" description="description3" activity_date="2012-03-13 13:13:13" />
	<activities activity_id="4" client_id="1" amount="4.0"
		commision="4.0" description="description1" activity_date="2012-01-11 11:11:11" />
	<activities activity_id="5" client_id="2" amount="5.0"
		commision="5.0" description="description2" activity_date="2012-02-12 12:12:12" />
	<activities activity_id="6" client_id="3" amount="6.0"
		commision="6.0" description="description3" activity_date="2012-03-13 13:13:13" />

	<deposites deposit_id="1" client_id="1" balance="1.0"
		closing_date="2012-12-11 11:11:11" opening_date="2012-11-11 11:11:11"
		type="LONG" />
	<deposites deposit_id="2" client_id="2" balance="2.0"
		closing_date="2012-12-12 12:12:12" opening_date="2012-11-12 11:12:12"
		type="SHORT" />
	<deposites deposit_id="3" client_id="1" balance="3.0"
		closing_date="2012-12-13 13:13:13" opening_date="2012-11-13 11:13:13"
		type="LONG" />
	<deposites deposit_id="4" client_id="2" balance="4.0"
		closing_date="2012-12-14 14:14:14" opening_date="2012-11-14 11:14:14"
		type="LONG" />
	<deposites deposit_id="5" client_id="3" balance="5.0"
		closing_date="2012-12-15 15:15:15" opening_date="2012-11-15 11:15:15"
		type="SHORT" />
	<deposites deposit_id="6" client_id="1" balance="6.0"
		closing_date="2012-12-16 16:16:16" opening_date="2012-11-16 11:16:16"
		type="LONG" />

	<properties prop_key="key1" prop_value="value1" />
	<properties prop_key="key2" prop_value="value2" />
	<properties prop_key="key3" prop_value="value3" />
</dataset>
